import { APP_EVENTS, dispatchAppEvent, readJson, writeJson } from './storageService';

const PRODUCTS_KEY = 'admin_products';

const coreProducts = [
  {
    id: 1,
    name: 'MacBook Pro 14" M3 Pro',
    price: 1999.99,
    oldPrice: 2199.99,
    description: 'Apple M3 Pro chip, 18GB RAM, 512GB SSD, and Liquid Retina XDR display.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 8,
    brand: 'Apple',
    rating: 4.8,
    isFeatured: true,
    featuredRank: 1,
    badge: 'Creator Pick',
    specs: { cpu: 'M3 Pro', ram: '18GB', storage: '512GB SSD' },
  },
  {
    id: 2,
    name: 'Dell XPS 15',
    price: 1899.99,
    description: 'Premium Windows ultrabook with OLED panel and RTX graphics.',
    image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 5,
    brand: 'Dell',
    rating: 4.6,
    isFeatured: true,
    featuredRank: 4,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 3,
    name: 'Lenovo ThinkPad X1 Carbon Gen 12',
    price: 1699.99,
    description: 'Ultra-light professional laptop with legendary keyboard and battery life.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 12,
    brand: 'Lenovo',
    rating: 4.7,
    isFeatured: true,
    featuredRank: 3,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 4,
    name: 'ASUS ROG Zephyrus G16',
    price: 2199.99,
    description: 'Gaming-focused powerhouse with RTX 4080 graphics and 240Hz display.',
    image: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 3,
    brand: 'ASUS',
    rating: 4.7,
    isFeatured: true,
    featuredRank: 2,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 5,
    name: 'HP Spectre x360 16',
    price: 1599.99,
    description: 'Convertible premium laptop with OLED display and all-day performance.',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 6,
    brand: 'HP',
    rating: 4.5,
    badge: 'Student Favorite',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 6,
    name: 'MSI Raider GE78 HX',
    price: 3299.99,
    description: 'Desktop-class gaming laptop built for creators and esports.',
    image: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 2,
    brand: 'MSI',
    rating: 4.6,
    badge: 'Pro Power',
    specs: { cpu: 'Intel Core i9', ram: '64GB', storage: '2TB SSD' },
  },
  {
    id: 7,
    name: 'Acer Swift X 14',
    price: 1499.99,
    oldPrice: 1649.99,
    description: 'Slim creator laptop with OLED display and RTX graphics for editing on the go.',
    image: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 9,
    brand: 'Acer',
    rating: 4.4,
    badge: 'Creator Pick',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 8,
    name: 'Razer Blade 16',
    price: 3499.99,
    oldPrice: 3699.99,
    description: 'Premium CNC gaming laptop with QHD+ display and top-tier performance.',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 4,
    brand: 'Razer',
    rating: 4.7,
    isFeatured: true,
    featuredRank: 5,
    badge: 'New',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '2TB SSD' },
  },
  {
    id: 9,
    name: 'Samsung Galaxy Book4 Ultra',
    price: 2399.99,
    description: 'Elegant premium notebook with AMOLED screen and strong creator performance.',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 7,
    brand: 'Samsung',
    rating: 4.5,
    badge: 'New',
    specs: { cpu: 'Intel Core Ultra 9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 10,
    name: 'Microsoft Surface Laptop Studio 2',
    price: 2799.99,
    oldPrice: 2999.99,
    description: 'Flexible premium laptop built for designers, developers, and hybrid workflows.',
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 6,
    brand: 'Microsoft',
    rating: 4.6,
    badge: 'Creator Pick',
    specs: { cpu: 'Intel Core i7', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 11,
    name: 'Gigabyte AERO 16 OLED',
    price: 2199.99,
    description: 'Color-accurate OLED laptop tuned for creators, 3D artists, and video teams.',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 5,
    brand: 'Gigabyte',
    rating: 4.5,
    badge: 'Creator Pick',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 12,
    name: 'Alienware m18',
    price: 3099.99,
    oldPrice: 3299.99,
    description: 'Large-screen gaming beast with powerful cooling and immersive performance.',
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 3,
    brand: 'Alienware',
    rating: 4.7,
    badge: 'New',
    specs: { cpu: 'AMD Ryzen 9', ram: '32GB', storage: '2TB SSD' },
  },
];

const additionalProducts = [
  {
    id: 13,
    name: 'Dell Latitude 9440 2-in-1',
    price: 2299.99,
    description: 'Executive business laptop with premium build, sharp display, and excellent conferencing tools.',
    image: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 10,
    brand: 'Dell',
    rating: 4.6,
    badge: 'Business Choice',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 14,
    name: 'HP Elite Dragonfly G4',
    price: 2149.99,
    oldPrice: 2299.99,
    description: 'Ultra-light premium business laptop built for travel-heavy professionals.',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 8,
    brand: 'HP',
    rating: 4.5,
    badge: 'New',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 15,
    name: 'Lenovo ThinkPad T14s Gen 5',
    price: 1799.99,
    description: 'Reliable business machine with excellent keyboard, security, and all-day battery.',
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 11,
    brand: 'Lenovo',
    rating: 4.6,
    badge: 'Best Seller',
    specs: { cpu: 'AMD Ryzen 7 Pro', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 16,
    name: 'Microsoft Surface Laptop 6',
    price: 1699.99,
    description: 'Clean premium Windows laptop with strong productivity focus and excellent build quality.',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 9,
    brand: 'Microsoft',
    rating: 4.5,
    badge: 'Business Choice',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 17,
    name: 'LG Gram 17 Pro',
    price: 1899.99,
    oldPrice: 2049.99,
    description: 'Large-screen productivity laptop that stays impressively light for travel and work.',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 7,
    brand: 'LG',
    rating: 4.4,
    badge: 'New',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 18,
    name: 'Framework Laptop 13',
    price: 1499.99,
    description: 'Repairable and upgradeable notebook designed for long-term ownership.',
    image: 'https://images.unsplash.com/photo-1593642532454-e138e28a63f4?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 13,
    brand: 'Framework',
    rating: 4.6,
    badge: 'Student Favorite',
    specs: { cpu: 'Intel Core Ultra 5', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 19,
    name: 'Acer TravelMate P6',
    price: 1599.99,
    description: 'Slim business ultrabook with enterprise durability and strong battery life.',
    image: 'https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 10,
    brand: 'Acer',
    rating: 4.3,
    badge: 'Business Choice',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 20,
    name: 'Samsung Galaxy Book4 Pro',
    price: 1799.99,
    description: 'Thin AMOLED productivity laptop with polished design and premium portability.',
    image: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 6,
    brand: 'Samsung',
    rating: 4.4,
    badge: 'New',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 21,
    name: 'Alienware x16 R2',
    price: 2899.99,
    oldPrice: 3099.99,
    description: 'High-end gaming laptop with bold design, advanced cooling, and premium performance.',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 5,
    brand: 'Alienware',
    rating: 4.7,
    badge: 'Pro Power',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 22,
    name: 'Lenovo Legion Pro 7i',
    price: 2599.99,
    description: 'Serious gaming system with fast display, strong thermals, and flagship performance.',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 8,
    brand: 'Lenovo',
    rating: 4.7,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 23,
    name: 'ASUS TUF Gaming A15',
    price: 1399.99,
    oldPrice: 1499.99,
    description: 'Durable gaming laptop with strong value, high refresh display, and solid cooling.',
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 12,
    brand: 'ASUS',
    rating: 4.4,
    badge: 'Best Seller',
    specs: { cpu: 'AMD Ryzen 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 24,
    name: 'MSI Stealth 16 AI Studio',
    price: 2499.99,
    description: 'Slim premium performance laptop for gamers and creators who travel often.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 6,
    brand: 'MSI',
    rating: 4.5,
    badge: 'New',
    specs: { cpu: 'Intel Core Ultra 9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 25,
    name: 'Acer Predator Helios 16',
    price: 2099.99,
    description: 'Powerful gaming laptop with excellent cooling and bright high-refresh panel.',
    image: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 7,
    brand: 'Acer',
    rating: 4.5,
    badge: 'Gaming Pick',
    specs: { cpu: 'Intel Core i9', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 26,
    name: 'HP Omen Transcend 16',
    price: 2199.99,
    oldPrice: 2349.99,
    description: 'Premium gaming laptop tuned for both esports and creator workloads.',
    image: 'https://images.unsplash.com/photo-1516387938699-a93567ec168e?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 6,
    brand: 'HP',
    rating: 4.5,
    badge: 'New',
    specs: { cpu: 'Intel Core i7', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 27,
    name: 'Gigabyte AORUS 17X',
    price: 2799.99,
    description: 'Large gaming workstation with desktop-class power and aggressive cooling.',
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 4,
    brand: 'Gigabyte',
    rating: 4.6,
    badge: 'Pro Power',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '2TB SSD' },
  },
  {
    id: 28,
    name: 'Razer Blade 14',
    price: 2699.99,
    description: 'Compact luxury gaming laptop with premium materials and powerful internals.',
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 5,
    brand: 'Razer',
    rating: 4.6,
    badge: 'Gaming Pick',
    specs: { cpu: 'AMD Ryzen 9', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 29,
    name: 'Dell G16',
    price: 1499.99,
    description: 'Well-balanced gaming laptop for players wanting strong performance at a better price.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 12,
    brand: 'Dell',
    rating: 4.4,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 30,
    name: 'ASUS ROG Strix Scar 18',
    price: 3399.99,
    oldPrice: 3599.99,
    description: 'Flagship giant-screen gaming laptop with elite performance and immersive display.',
    image: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=800&h=600&fit=crop',
    category: 'Gaming',
    stock: 4,
    brand: 'ASUS',
    rating: 4.8,
    badge: 'Pro Power',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '2TB SSD' },
  },
  {
    id: 31,
    name: 'ASUS ProArt Studiobook 16 OLED',
    price: 2599.99,
    description: 'Creator-focused performance laptop with color-accurate display and studio-grade power.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 7,
    brand: 'ASUS',
    rating: 4.6,
    badge: 'Creator Pick',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 32,
    name: 'Dell Precision 5680',
    price: 2899.99,
    oldPrice: 3099.99,
    description: 'Mobile workstation for CAD, rendering, and heavy creative production.',
    image: 'https://images.unsplash.com/photo-1537498425277-c283d32ef9db?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 6,
    brand: 'Dell',
    rating: 4.7,
    badge: 'Creator Pick',
    specs: { cpu: 'Intel Core i9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 33,
    name: 'MacBook Pro 16 M3 Max',
    price: 3899.99,
    description: 'Flagship Apple creator notebook for filmmakers, designers, and developers.',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 5,
    brand: 'Apple',
    rating: 4.9,
    isFeatured: true,
    featuredRank: 6,
    badge: 'Creator Pick',
    specs: { cpu: 'M3 Max', ram: '36GB', storage: '1TB SSD' },
  },
  {
    id: 34,
    name: 'Acer Swift Go 16 OLED',
    price: 1299.99,
    oldPrice: 1399.99,
    description: 'Portable OLED laptop for students and creators who need vibrant visuals and value.',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 10,
    brand: 'Acer',
    rating: 4.4,
    badge: 'Student Favorite',
    specs: { cpu: 'Intel Core Ultra 5', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 35,
    name: 'HP Envy 16',
    price: 1699.99,
    description: 'Creator laptop with strong multimedia performance and a premium design.',
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 8,
    brand: 'HP',
    rating: 4.5,
    badge: 'Creator Pick',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 36,
    name: 'Lenovo Yoga Pro 9i',
    price: 1999.99,
    description: 'Premium performance ultrabook for content creation and creative multitasking.',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 9,
    brand: 'Lenovo',
    rating: 4.6,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core Ultra 9', ram: '32GB', storage: '1TB SSD' },
  },
  {
    id: 37,
    name: 'LG Gram Pro 16',
    price: 1999.99,
    description: 'Large, lightweight creator laptop with sharp display and great mobility.',
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 7,
    brand: 'LG',
    rating: 4.4,
    badge: 'New',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 38,
    name: 'Framework Laptop 16',
    price: 1899.99,
    description: 'Modular large-format laptop for creators and tinkerers who value repairability.',
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&h=600&fit=crop',
    category: 'Creator',
    stock: 6,
    brand: 'Framework',
    rating: 4.5,
    badge: 'New',
    specs: { cpu: 'AMD Ryzen 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 39,
    name: 'MacBook Air 13 M2',
    price: 1099.99,
    oldPrice: 1199.99,
    description: 'Lightweight student-friendly MacBook with excellent battery life and smooth performance.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 14,
    brand: 'Apple',
    rating: 4.8,
    badge: 'Student Favorite',
    specs: { cpu: 'M2', ram: '8GB', storage: '256GB SSD' },
  },
  {
    id: 40,
    name: 'HP Pavilion Plus 14',
    price: 999.99,
    description: 'Balanced student laptop with solid performance, clean design, and good display.',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 16,
    brand: 'HP',
    rating: 4.3,
    badge: 'Student Favorite',
    specs: { cpu: 'Intel Core i5', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 41,
    name: 'Lenovo IdeaPad Slim 5',
    price: 899.99,
    oldPrice: 999.99,
    description: 'Affordable daily-use laptop ideal for campus work, browsing, and streaming.',
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 20,
    brand: 'Lenovo',
    rating: 4.2,
    badge: 'Best Seller',
    specs: { cpu: 'AMD Ryzen 5', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 42,
    name: 'Dell Inspiron 14 Plus',
    price: 1049.99,
    description: 'Flexible mid-range laptop with enough power for students and multitaskers.',
    image: 'https://images.unsplash.com/photo-1593642532454-e138e28a63f4?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 15,
    brand: 'Dell',
    rating: 4.3,
    badge: 'Student Favorite',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 43,
    name: 'ASUS Zenbook 14 OLED',
    price: 1199.99,
    description: 'Stylish student and creator hybrid laptop with OLED display and premium feel.',
    image: 'https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 11,
    brand: 'ASUS',
    rating: 4.5,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core Ultra 5', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 44,
    name: 'Acer Aspire 5',
    price: 749.99,
    description: 'Budget-friendly laptop for everyday work, classes, and casual productivity.',
    image: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 18,
    brand: 'Acer',
    rating: 4.1,
    badge: 'Budget Pick',
    specs: { cpu: 'Intel Core i5', ram: '8GB', storage: '512GB SSD' },
  },
  {
    id: 45,
    name: 'Samsung Galaxy Book3 360',
    price: 1299.99,
    description: 'Convertible AMOLED laptop for students who want flexibility and portability.',
    image: 'https://images.unsplash.com/photo-1516387938699-a93567ec168e?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 9,
    brand: 'Samsung',
    rating: 4.3,
    badge: 'Student Favorite',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 46,
    name: 'Surface Laptop Go 3',
    price: 999.99,
    description: 'Compact lightweight laptop for students who want premium feel at a friendlier size.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 10,
    brand: 'Microsoft',
    rating: 4.2,
    badge: 'Student Favorite',
    specs: { cpu: 'Intel Core i5', ram: '8GB', storage: '256GB SSD' },
  },
  {
    id: 47,
    name: 'LG Gram 14',
    price: 1299.99,
    oldPrice: 1399.99,
    description: 'Featherweight student and travel laptop with excellent battery life.',
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 8,
    brand: 'LG',
    rating: 4.3,
    badge: 'New',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 48,
    name: 'Huawei MateBook 14',
    price: 1099.99,
    description: 'Sleek student productivity laptop with high-resolution display and premium finish.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 10,
    brand: 'Huawei',
    rating: 4.2,
    badge: 'New',
    specs: { cpu: 'Intel Core i5', ram: '16GB', storage: '512GB SSD' },
  },
  {
    id: 49,
    name: 'Acer Chromebook Plus 515',
    price: 549.99,
    description: 'Simple and affordable ChromeOS laptop for classes, browsing, and documents.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 22,
    brand: 'Acer',
    rating: 4.0,
    badge: 'Budget Pick',
    specs: { cpu: 'Intel Core i3', ram: '8GB', storage: '256GB SSD' },
  },
  {
    id: 50,
    name: 'MSI Prestige 14 AI Evo',
    price: 1499.99,
    description: 'Portable premium productivity laptop built for students and young professionals.',
    image: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 9,
    brand: 'MSI',
    rating: 4.3,
    badge: 'New',
    specs: { cpu: 'Intel Core Ultra 7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 51,
    name: 'Dell Inspiron 16 Plus',
    price: 1399.99,
    description: 'Versatile large-screen laptop for students, creators, and productivity workflows.',
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&h=600&fit=crop',
    category: 'Student',
    stock: 12,
    brand: 'Dell',
    rating: 4.4,
    badge: 'Best Seller',
    specs: { cpu: 'Intel Core i7', ram: '16GB', storage: '1TB SSD' },
  },
  {
    id: 52,
    name: 'Lenovo ThinkBook 14 2-in-1',
    price: 1249.99,
    description: 'Convertible business-student hybrid laptop with flexible use and strong value.',
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&h=600&fit=crop',
    category: 'Business',
    stock: 11,
    brand: 'Lenovo',
    rating: 4.3,
    badge: 'New',
    specs: { cpu: 'Intel Core Ultra 5', ram: '16GB', storage: '512GB SSD' },
  },
];

export const defaultProducts = [...coreProducts, ...additionalProducts];

const sanitizeProduct = (product, fallbackId) => ({
  id: Number(product.id ?? fallbackId),
  name: product.name?.trim() || 'Untitled Product',
  category: product.category?.trim() || 'Laptops',
  description: product.description?.trim() || 'Premium laptop from Kamran Laptop Hub.',
  image: product.image?.trim() || '',
  brand: product.brand?.trim() || product.category?.trim() || 'Laptop',
  badge: product.badge?.trim() || undefined,
  isFeatured: Boolean(product.isFeatured),
  featuredRank: product.featuredRank ? Math.max(1, Number(product.featuredRank) || 1) : undefined,
  price: Math.max(0, Number(product.price) || 0),
  oldPrice: product.oldPrice ? Math.max(0, Number(product.oldPrice) || 0) : undefined,
  stock: Math.max(0, Number(product.stock) || 0),
  rating: Number(product.rating) || 4.5,
  specs: product.specs || {},
});

const mergeMissingDefaults = (products) => {
  const existingIds = new Set(products.map((product) => Number(product.id)));
  const missingDefaults = defaultProducts.filter((product) => !existingIds.has(Number(product.id)));

  if (!missingDefaults.length) return products;
  return saveProducts([...products, ...missingDefaults]);
};

const saveProducts = (products) => {
  const nextProducts = products.map((product, index) => sanitizeProduct(product, index + 1));
  writeJson(PRODUCTS_KEY, nextProducts);
  dispatchAppEvent(APP_EVENTS.productsChanged, nextProducts);
  return nextProducts;
};

export const getProducts = () => {
  const existing = readJson(PRODUCTS_KEY, null);
  if (existing?.length) {
    const sanitized = existing.map((product, index) => sanitizeProduct(product, index + 1));
    return mergeMissingDefaults(sanitized);
  }
  return saveProducts(defaultProducts);
};

export const getProductById = (id) =>
  getProducts().find((product) => Number(product.id) === Number(id)) || null;

export const createProduct = async (product) => {
  const products = getProducts();
  const nextId = products.length ? Math.max(...products.map((item) => Number(item.id))) + 1 : 1;
  return saveProducts([...products, sanitizeProduct(product, nextId)]);
};

export const updateProduct = async (productId, updates) => {
  const products = getProducts().map((product) =>
    Number(product.id) === Number(productId)
      ? sanitizeProduct({ ...product, ...updates }, product.id)
      : product
  );
  return saveProducts(products);
};

export const deleteProduct = async (productId) => {
  const products = getProducts().filter((product) => Number(product.id) !== Number(productId));
  return saveProducts(products);
};

export const resetProducts = async () => saveProducts(defaultProducts);
